# Generated by Django 5.1.6 on 2025-02-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uidesigners',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='uidesigners',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
