# Generated by Django 5.1.6 on 2025-02-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_name_uidesigners_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uidesigners',
            old_name='destination',
            new_name='designation',
        ),
    ]
