# Generated by Django 5.1.6 on 2025-02-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_rename_destination_uidesigners_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=255, null=True)),
                ('date_of_join', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=255, null=True)),
                ('date_of_join', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=255, null=True)),
                ('date_of_join', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uidesigners',
            name='phone',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
