# Generated by Django 5.1.6 on 2025-02-11 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Document', 'Document'), ('UI', 'UI'), ('Development', 'Development'), ('Testing', 'Testing'), ('Launch', 'Launch')], default='Not Started', max_length=20)),
                ('adv_pay', models.BooleanField(default=True)),
                ('adv_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_pay', models.BooleanField(default=True)),
                ('full_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.client')),
            ],
        ),
    ]
