# Generated by Django 5.1.6 on 2025-02-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.client'),
        ),
    ]
